baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Asish Kumar - Software Engineer in India'
theme = 'devise'
enableEmoji = true
relativeURLs = true
enableRobotsTXT = true
copyright = '&copy; Copyright 2024, Asish Kumar'

[menu]
  [[menu.main]]
    identifier = "blogs"
    name = "Blogs"
    title = "Blogs"
    url = "/Blogs/"
    weight = -100

[params] 
    header_title = "Asish Kumar"
    header_subtitle = "burner of poptarts; breaker of things"
    recent_posts = 5
    [params.style]                             # CSS style overrides
        backgroundColor = '#131418'
        homeImageBorderColor = '#ffffff'
        fontFamilyBase = 'Roboto' 
        fontColor = '#babdc4'
    [[params.social]]
        fa_icon = "fab fa-linkedin-in fa-1x"
        href = "https://www.linkedin.com/in/asish-kr/"
    [[params.social]]
        fa_icon = "fab fa-github fa-1x"
        href = "http://github.com/officialasishkumar"
    
[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files
